language: python
before_install:
- pip install pycodestyle
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=artellapipe
- sphinx-apidoc -f -e -o docs/sphinx artellapipe
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: jHafDJSYowWY6cMyEqS+ek6hq4/ruPbMO5A6FV3RWunMABM9lZvLEfLVv2vsMIMma4sjkulDR4+MB76LsvWhp8pNZ9xQn81WBA/lfb4PH5Km1npmAKcBpgcBPknHNve9ph1Nj+gOaiDZHXtK8cbng2o8v31f43igvT+QibCLbaTEtJ6y/aF7ZNIKonycLzlo4hvZfK3GPYqbvlNlwBOItHVxi6PUepxyHBuQ4aoTtKxfzt6Q9fBNuYSr7qSvP3tZ08PyMYkuAwGexb1LbzMqsOGxUhVlAS0aFFrihGevbqryTcHadnLKpBzARlkZOUei+dx4RahWnuVJWhEVc6WKdLi1spEtZE9avuZS9AH7lsJ+9fG/dFehD5a9b/MAzi8ymGWPOKUnGscc8pkvRx5b1sk5Tj+8IhkxqjgXw4MwKFRO1vjIO+AjtPEOM2yTpzo92ScoIB8JXroiXHCBHpl21qFdOaMs9sr9rW+hR10N8QQ3mHhKqQrpmBcV5+yBzRDpqireqdejsLceOFMZ3nn3EGrVp4bJR5PROa/82BYUDgQW57VlXm49QYpWnOwz4kPRR7BGyYwkqDssZ+pNnC5nhek8xhFeei8u1VvWWjjCzeg0kSh1WX7gcVTMHuXZCcooT7YVsKfRq8aJA8/tA5CJr2LwY7FDezBkSeyE4rNVI0I=
    on:
      branch: master
      tags: true